name: Python CI

on:
  push:
    branches: [ "main" ]  # запуск при пуше в main
  pull_request:
    branches: [ "main" ]  # и при PR

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Клонировать репозиторий
      uses: actions/checkout@v3

    - name: 🐍 Установить Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: ⚙️ Установить зависимости
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov

    - name: 🧪 Запустить тесты с покрытием
      run: |
        pytest --cov=car_rental --cov-report=term

    - name: 💾 Сохранить HTML-отчет покрытия (опционально)
      if: always()
      run: |
        pytest --cov=car_rental --cov-report=html
        mkdir -p coverage_report
        cp -r htmlcov/* coverage_report/
      continue-on-error: true

    - name: 📤 Загрузить отчет (опционально)
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-html
        path: coverage_report/
